"""create scraped_articles table

Revision ID: 11379adbc4ae
Revises: 
Create Date: 2026-03-02 20:40:15.845058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11379adbc4ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.String(length=128), nullable=False),
    sa.Column('guid', sa.String(length=512), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('top_image', sa.String(length=2048), nullable=False),
    sa.Column('is_content_extracted', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraped_articles_content_hash'), 'scraped_articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_scraped_articles_source'), 'scraped_articles', ['source'], unique=False)
    op.create_index(op.f('ix_scraped_articles_url'), 'scraped_articles', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_articles_url'), table_name='scraped_articles')
    op.drop_index(op.f('ix_scraped_articles_source'), table_name='scraped_articles')
    op.drop_index(op.f('ix_scraped_articles_content_hash'), table_name='scraped_articles')
    op.drop_table('scraped_articles')
    # ### end Alembic commands ###
