"""add_news_priority_columns_and_source_config

Revision ID: 68db84efce21
Revises: e0da9b4c2b1b
Create Date: 2026-03-07 16:03:38.239770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68db84efce21'
down_revision: Union[str, Sequence[str], None] = 'e0da9b4c2b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_config_source_name'), 'source_config', ['source_name'], unique=True)
    op.add_column('scraped_articles', sa.Column('importance_score', sa.Float(), nullable=True))
    op.add_column('scraped_articles', sa.Column('topic_cluster_id', sa.String(length=64), nullable=True))
    op.add_column('scraped_articles', sa.Column('cluster_label', sa.String(length=256), nullable=False, server_default=''))
    op.add_column('scraped_articles', sa.Column('domain', sa.String(length=64), nullable=False, server_default=''))
    op.create_index(op.f('ix_scraped_articles_importance_score'), 'scraped_articles', ['importance_score'], unique=False)
    op.create_index(op.f('ix_scraped_articles_topic_cluster_id'), 'scraped_articles', ['topic_cluster_id'], unique=False)
    # ### end Alembic commands ###

    # Seed known source credibility scores
    op.execute("""
        INSERT INTO source_config (source_name, credibility_score, active, notes) VALUES
        ('BBC',               0.95, true, 'British Broadcasting Corporation'),
        ('Washington Post',   0.90, true, 'US national broadsheet'),
        ('The Hindu',         0.85, true, 'Indian broadsheet, strong policy coverage'),
        ('Live Mint',         0.80, true, 'Indian financial daily'),
        ('Economic Times',    0.80, true, 'Indian business newspaper'),
        ('NDTV',              0.78, true, 'Indian TV news network'),
        ('India Today',       0.75, true, 'Indian news magazine and TV'),
        ('India TV',          0.65, true, 'Indian Hindi-language TV news')
        ON CONFLICT (source_name) DO NOTHING;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraped_articles_topic_cluster_id'), table_name='scraped_articles')
    op.drop_index(op.f('ix_scraped_articles_importance_score'), table_name='scraped_articles')
    op.drop_column('scraped_articles', 'domain')
    op.drop_column('scraped_articles', 'cluster_label')
    op.drop_column('scraped_articles', 'topic_cluster_id')
    op.drop_column('scraped_articles', 'importance_score')
    op.drop_index(op.f('ix_source_config_source_name'), table_name='source_config')
    op.drop_table('source_config')
    # ### end Alembic commands ###
