"""create_entity_aliases_table

Revision ID: 773351ebf854
Revises: 11379adbc4ae
Create Date: 2026-03-04 17:47:18.538977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773351ebf854'
down_revision: Union[str, Sequence[str], None] = '11379adbc4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('canonical', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=True)
    op.create_index(op.f('ix_entity_aliases_canonical'), 'entity_aliases', ['canonical'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_aliases_canonical'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    # ### end Alembic commands ###
