"""Add refactoring models: entity_type_domain_mappings, weather_thresholds, scoring_weights, city_metadata, coordination_patterns, india_seed_entities

Revision ID: 78f58163f9ea
Revises: b2c3d4e5f6a7
Create Date: 2026-03-27 02:11:51.423641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78f58163f9ea'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('elevation_meters', sa.Float(), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('is_india_seed', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_metadata_city_name'), 'city_metadata', ['city_name'], unique=True)
    op.create_table('coordination_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_id', sa.String(length=100), nullable=False),
    sa.Column('source_cluster', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('coordination_score', sa.Float(), nullable=False),
    sa.Column('message_similarity', sa.Float(), nullable=False),
    sa.Column('timing_correlation', sa.Float(), nullable=False),
    sa.Column('network_density', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordination_patterns_pattern_id'), 'coordination_patterns', ['pattern_id'], unique=True)
    op.create_index(op.f('ix_coordination_patterns_time_window_start'), 'coordination_patterns', ['time_window_start'], unique=False)
    op.create_table('entity_type_domain_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('primary_domain', sa.String(length=50), nullable=False),
    sa.Column('secondary_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_type_domain_mappings_entity_type'), 'entity_type_domain_mappings', ['entity_type'], unique=True)
    op.create_table('india_seed_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('connection_count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('discovered_via', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_india_seed_entities_entity_name'), 'india_seed_entities', ['entity_name'], unique=True)
    op.create_index(op.f('ix_india_seed_entities_entity_type'), 'india_seed_entities', ['entity_type'], unique=False)
    op.create_table('scoring_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('weight_type', sa.String(length=100), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('weight_value', sa.Float(), nullable=False),
    sa.Column('last_calibrated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weight_type', 'component_name', 'version', name='uq_scoring_weight')
    )
    op.create_index(op.f('ix_scoring_weights_component_name'), 'scoring_weights', ['component_name'], unique=False)
    op.create_index(op.f('ix_scoring_weights_weight_type'), 'scoring_weights', ['weight_type'], unique=False)
    op.create_table('weather_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('threshold_type', sa.String(length=50), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('departure_value', sa.Float(), nullable=True),
    sa.Column('consecutive_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'zone', 'season', 'threshold_type', name='uq_weather_threshold')
    )
    op.create_index(op.f('ix_weather_thresholds_city'), 'weather_thresholds', ['city'], unique=False)
    op.create_index(op.f('ix_weather_thresholds_threshold_type'), 'weather_thresholds', ['threshold_type'], unique=False)
    op.create_index(op.f('ix_weather_thresholds_zone'), 'weather_thresholds', ['zone'], unique=False)
    op.drop_index(op.f('ix_detected_signals_detected_at'), table_name='detected_signals')
    op.drop_index(op.f('ix_detected_signals_expires_at'), table_name='detected_signals')
    op.drop_index(op.f('ix_detected_signals_signal_type'), table_name='detected_signals')
    op.drop_table('detected_signals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('cluster_label', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('spike_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('baseline_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('detected_signals_pkey')),
    sa.UniqueConstraint('signal_type', 'entity_name', 'cluster_id', 'detected_at', name=op.f('uq_signal_subject_detected_at'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_detected_signals_signal_type'), 'detected_signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_detected_signals_expires_at'), 'detected_signals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_detected_signals_detected_at'), 'detected_signals', ['detected_at'], unique=False)
    op.drop_index(op.f('ix_weather_thresholds_zone'), table_name='weather_thresholds')
    op.drop_index(op.f('ix_weather_thresholds_threshold_type'), table_name='weather_thresholds')
    op.drop_index(op.f('ix_weather_thresholds_city'), table_name='weather_thresholds')
    op.drop_table('weather_thresholds')
    op.drop_index(op.f('ix_scoring_weights_weight_type'), table_name='scoring_weights')
    op.drop_index(op.f('ix_scoring_weights_component_name'), table_name='scoring_weights')
    op.drop_table('scoring_weights')
    op.drop_index(op.f('ix_india_seed_entities_entity_type'), table_name='india_seed_entities')
    op.drop_index(op.f('ix_india_seed_entities_entity_name'), table_name='india_seed_entities')
    op.drop_table('india_seed_entities')
    op.drop_index(op.f('ix_entity_type_domain_mappings_entity_type'), table_name='entity_type_domain_mappings')
    op.drop_table('entity_type_domain_mappings')
    op.drop_index(op.f('ix_coordination_patterns_time_window_start'), table_name='coordination_patterns')
    op.drop_index(op.f('ix_coordination_patterns_pattern_id'), table_name='coordination_patterns')
    op.drop_table('coordination_patterns')
    op.drop_index(op.f('ix_city_metadata_city_name'), table_name='city_metadata')
    op.drop_table('city_metadata')
    # ### end Alembic commands ###
