"""add_context_type_and_seed_aliases

Revision ID: ab1e26709819
Revises: 773351ebf854
Create Date: 2026-03-04 19:13:16.314856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1e26709819'
down_revision: Union[str, Sequence[str], None] = '773351ebf854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_aliases', sa.Column('context_type', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=False)
    op.create_unique_constraint('uq_alias_context', 'entity_aliases', ['alias', 'context_type'])
    # ### end Alembic commands ###

    # --- Seed aliases ---
    # context_type=None → always apply (type-independent)
    # context_type="Country" → only when entity tagged as Country (metonyms)
    entity_aliases = sa.table(
        'entity_aliases',
        sa.column('alias', sa.String),
        sa.column('canonical', sa.String),
        sa.column('entity_type', sa.String),
        sa.column('context_type', sa.String),
        sa.column('confidence', sa.Float),
        sa.column('resolved_by', sa.String),
    )

    seeds = [
        # --- Type-independent aliases (context_type=NULL) ---
        # United States
        ("us", "United States", "Country", None),
        ("usa", "United States", "Country", None),
        ("u.s.", "United States", "Country", None),
        ("u.s.a.", "United States", "Country", None),
        ("america", "United States", "Country", None),
        ("united states of america", "United States", "Country", None),
        # United Kingdom
        ("uk", "United Kingdom", "Country", None),
        ("u.k.", "United Kingdom", "Country", None),
        ("britain", "United Kingdom", "Country", None),
        ("great britain", "United Kingdom", "Country", None),
        # China
        ("prc", "China", "Country", None),
        ("people's republic of china", "China", "Country", None),
        ("mainland china", "China", "Country", None),
        # International orgs
        ("eu", "European Union", "Organization", None),
        ("nato", "North Atlantic Treaty Organization", "Organization", None),
        ("un", "United Nations", "Organization", None),
        ("imf", "International Monetary Fund", "Organization", None),
        ("uae", "United Arab Emirates", "Country", None),
        ("dprk", "North Korea", "Country", None),
        ("rok", "South Korea", "Country", None),
        # US agencies
        ("dod", "United States Department of Defense", "Organization", None),
        ("cia", "Central Intelligence Agency", "Organization", None),
        ("fbi", "Federal Bureau of Investigation", "Organization", None),
        ("nsa", "National Security Agency", "Organization", None),
        # People
        ("pm modi", "Narendra Modi", "Person", None),
        ("modi", "Narendra Modi", "Person", None),
        ("trump", "Donald Trump", "Person", None),
        ("biden", "Joe Biden", "Person", None),
        ("president xi", "Xi Jinping", "Person", None),
        ("xi", "Xi Jinping", "Person", None),
        ("putin", "Vladimir Putin", "Person", None),
        ("zelensky", "Volodymyr Zelensky", "Person", None),
        ("zelenskyy", "Volodymyr Zelensky", "Person", None),
        # WHO — type-gated to Organization only (avoid "who" in text)
        ("who", "World Health Organization", "Organization", "Organization"),
        # Soviet Union
        ("ussr", "Soviet Union", "Country", None),

        # --- Type-gated metonyms (only fire when entity matches context_type) ---
        # Capital-as-country metonyms: only when tagged Country
        ("beijing", "China", "Country", "Country"),
        ("moscow", "Russia", "Country", "Country"),
        ("washington", "United States", "Country", "Country"),
        ("tehran", "Iran", "Country", "Country"),
        ("pyongyang", "North Korea", "Country", "Country"),
        ("jerusalem", "Israel", "Country", "Country"),
        ("ankara", "Turkey", "Country", "Country"),
        ("new delhi", "India", "Country", "Country"),
        ("tokyo", "Japan", "Country", "Country"),
        ("london", "United Kingdom", "Country", "Country"),
        ("paris", "France", "Country", "Country"),
        ("berlin", "Germany", "Country", "Country"),
        # Building-as-org metonyms: only when tagged Organization
        ("pentagon", "United States Department of Defense", "Organization", "Organization"),
        ("kremlin", "Russian Government", "Organization", "Organization"),
        ("white house", "United States Government", "Organization", "Organization"),
        ("downing street", "United Kingdom Government", "Organization", "Organization"),
    ]

    op.bulk_insert(entity_aliases, [
        {
            "alias": alias,
            "canonical": canonical,
            "entity_type": etype,
            "context_type": ctx,
            "confidence": 1.0,
            "resolved_by": "seed",
        }
        for alias, canonical, etype, ctx in seeds
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_alias_context', 'entity_aliases', type_='unique')
    op.drop_index(op.f('ix_entity_aliases_alias'), table_name='entity_aliases')
    op.create_index(op.f('ix_entity_aliases_alias'), 'entity_aliases', ['alias'], unique=True)
    op.drop_column('entity_aliases', 'context_type')
    # ### end Alembic commands ###
