"""add weather tables

Revision ID: e0da9b4c2b1b
Revises: ab1e26709819
Create Date: 2026-03-07 15:02:54.683228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e0da9b4c2b1b'
down_revision: Union[str, Sequence[str], None] = 'ab1e26709819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('climate_normals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('variable', sa.String(length=64), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('std', sa.Float(), nullable=False),
    sa.Column('p5', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('p95', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'month', 'variable', name='uq_climate_normal')
    )
    op.create_index(op.f('ix_climate_normals_city'), 'climate_normals', ['city'], unique=False)
    op.create_table('weather_anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('peak_value', sa.Float(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_anomalies_anomaly_type'), 'weather_anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_weather_anomalies_city'), 'weather_anomalies', ['city'], unique=False)
    op.create_index(op.f('ix_weather_anomalies_start_date'), 'weather_anomalies', ['start_date'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_mean', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_max', sa.Float(), nullable=True),
    sa.Column('apparent_temperature_min', sa.Float(), nullable=True),
    sa.Column('precipitation_sum', sa.Float(), nullable=True),
    sa.Column('rain_sum', sa.Float(), nullable=True),
    sa.Column('snowfall_sum', sa.Float(), nullable=True),
    sa.Column('precipitation_hours', sa.Float(), nullable=True),
    sa.Column('wind_speed_max', sa.Float(), nullable=True),
    sa.Column('wind_gusts_max', sa.Float(), nullable=True),
    sa.Column('humidity_mean', sa.Float(), nullable=True),
    sa.Column('soil_moisture_mean', sa.Float(), nullable=True),
    sa.Column('et0_evapotranspiration', sa.Float(), nullable=True),
    sa.Column('shortwave_radiation_sum', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('temp_max_zscore', sa.Float(), nullable=True),
    sa.Column('temp_min_zscore', sa.Float(), nullable=True),
    sa.Column('precip_zscore', sa.Float(), nullable=True),
    sa.Column('soil_moisture_zscore', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'date', name='uq_weather_obs_city_date')
    )
    op.create_index(op.f('ix_weather_observations_city'), 'weather_observations', ['city'], unique=False)
    op.create_index(op.f('ix_weather_observations_date'), 'weather_observations', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_date'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_city'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_weather_anomalies_start_date'), table_name='weather_anomalies')
    op.drop_index(op.f('ix_weather_anomalies_city'), table_name='weather_anomalies')
    op.drop_index(op.f('ix_weather_anomalies_anomaly_type'), table_name='weather_anomalies')
    op.drop_table('weather_anomalies')
    op.drop_index(op.f('ix_climate_normals_city'), table_name='climate_normals')
    op.drop_table('climate_normals')
    # ### end Alembic commands ###
